SELECT RIDER_NAME,COUNT(*) FROM RIDES WHERE RIDE_STATUS ='cancelled' GROUP BY RIDER_NAME 

--NUMBER OF ROWS
SELECT COUNT(*) FROM RIDES


--10 ROWS ONLY
SELECT * FROM RIDES LIMIT 10


--SELECT ONLY SPECIFIC ROWS
SELECT DRIVER_NAME, PIVCKUP_CITY , FARE_AMOUNT FROM RIDES

--SELECT ONLY CANCELLED RIDES
SELECT DRIVER_NAME, PICKUP_CITY, DROPOFF_CITY ,FARE_AMOUNT FROM  RIDES


--CHANGE COLUMN NAME
ALTER TABLE RIDES RENAME COLUMN PIVCKUP_CITY TO PICKUP_CITY;


--RIDE STARTED FROM KATHMANDU
SELECT * FROM RIDES WHERE PICKUP_CITY ='KATHMANDU' OR PICKUP_CITY='KATHMANDU'

--CITY WITH MOST CANCELLED RIDES
SELECT PICKUP_CITY,COUNT(*) AS NUM_OF_CANCELLED_RIDES FROM RIDES GROUP BY PICKUP_CITY ORDER BY NUM_OF_CANCELLED_RIDES DESC

--RIDE STARTED FROM KATHMANDU AND FARE GREATER THAN 300
SELECT * FROM RIDES WHERE PICKUP_CITY='KATHMANDU' AND FARE_AMOUNT >=300 

--EITHER PICKUP CITY KATHMANDU OR POKHARA
SELECT * FROM RIDES WHERE PICKUP_CITY='KATHMANDU' OR PICKUP_CITY ='POKHARA'

--TOP 5 FARE
SELECT DRIVER_NAME , FARE_AMOUNT FROM RIDES ORDER BY FARE_AMOUNT DESC LIMIT 5 
SELECT DRIVER_NAME, SUM(FARE_AMOUNT) AS TOTAL_FARE FROM RIDES GROUP BY DRIVER_NAME ORDER BY TOTAL_FARE DESC LIMIT 5


--PASSENGER NAME WITH OLI IN THE NAME
SELECT * FROM RIDES WHERE RIDER_NAME LIKE '%OLI%' 
SELECT DISTINCT(RIDER_NAME) FROM RIDES WHERE RIDER_NAME LIKE '%OLI%' 
SELECT * FROM RIDES WHERE RIDER_NAME LIKE '_I%' 

--RATING NULL
SELECT * FROM RIDES WHERE RATING IS NULL 
SELECT COUNT(*) FROM RIDES WHERE RATING IS NULL

--PAYMENT METHOD THAT IS NOT CASH
SELECT * FROM RIDES WHERE PAYMENT_METHOD <> 'CASH'
SELECT COUNT(*) FROM RIDES WHERE PAYMENT_METHOD <> 'CASH' OR PAYMENT_METHOD  IS NULL
SELECT COUNT(*) FROM RIDES WHERE PAYMENT_METHOD='CASH'

SELECT 2693+2307


--RATING NULL
SELECT * FROM RIDES WHERE RATING IS NULL
SELECT COUNT(*) FROM RIDES WHERE RATING IS NULL

--SELET RATING NOT NULL
SELECT * FROM RIDES WHERE RATING IS NOT NULL
SELECT COUNT(*) FROM RIDES WHERE RATING IS NOT NULL

SELECT 2621+2379


--TOP 5 RIDES BY DISTANCE
SELECT * FROM RIDES ORDER BY RIDE_DISTANCE DESC LIMIT 5


--RIDES AFTER JANUARY 1
SELECT * FROM RIDES WHERE  COMPLETED_AT::DATE > '2024-06-01';
SELECT COUNT(*) FROM RIDES WHERE  COMPLETED_AT::DATE >= '2024-06-01';


--WEEK1: STRING OPERATION, TIMESTAMP FUNCTION



--PICKUP AND DROPOFF CITY SAME
SELECT * FROM RIDES WHERE PICKUP_CITY =DROPOFF_CITY 
SELECT COUNT(*) FROM RIDES WHERE PICKUP_CITY =DROPOFF_CITY 

SELECT * FROM RIDES WHERE PICKUP_CITY =DROPOFF_CITY AND  FARE_AMOUNT >200


--Insert Duplicate
INSERT INTO rides (driver_name,rider_name,pickup_city,dropoff_city,fare_amount,ride_distance,ride_status,requested_at,completed_at,rating,payment_method) VALUES
	 ('Bikash Karki','Sabina Dahal','Birgunj','Kathmandu',17.96,31.75,'completed','2024-10-27 12:16:55','2024-10-27 13:26:12.960719',4.6,'esewa');



--Voilating Constraint
INSERT INTO rides (ride,driver_name,rider_name,pickup_city,dropoff_city,fare_amount,ride_distance,ride_status,requested_at,completed_at,rating,payment_method) VALUES
	 (5001,'Bikash Karki','Sabina Dahal','Birgunj','Kathmandu',17.96,-100,'completed','2024-10-27 12:16:55','2024-10-27 13:26:12.960719',4.6,'esewa');




